apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: rabbitmq
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      
    alerting:
      alertmanagers:
        - static_configs:
            - targets:

    rule_files:

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "localhost:9090" ]
            labels:
              app: "prometheus"
      - job_name: "rabbitmq"
        static_configs:
          - targets: [ "rabbitmq-svc:15692" ]
            labels:
              app: "prometheus"