apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: rabbitmq
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer