kind: Service
apiVersion: v1
metadata:
  namespace: rabbitmq
  name: rabbitmq-svc
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
   - name: metrics
     protocol: TCP
     port: 15692
     targetPort: 15692
     nodePort: 32672
   - name: stream
     protocol: TCP
     targetPort: 5552
     port: 5552
     nodePort: 30673
  selector:
    app: rabbitmq